# **Data Import**

In [2]:
import pandas as pd
import numpy as np

Looking at the zipfile

In [3]:
import zipfile
# python module used to open, read and extraxt from zipfiles

with zipfile.ZipFile('t20s_male_csv2.zip', 'r') as all_it20s:
# turn the zipfile into an object so we can do some stuff wirh it
  it20s_namelist = all_it20s.namelist()
  print(it20s_namelist[:10])



['README.txt', '211048.csv', '211048_info.csv', '211028.csv', '211028_info.csv', '222678.csv', '222678_info.csv', '226374.csv', '226374_info.csv', '237242.csv']


In [4]:
len(it20s_namelist)

5241

In [5]:
with zipfile.ZipFile('t20s_male_csv2.zip', 'r') as all_it20s: # have to use zoipfile each time to access the zip
    with all_it20s.open('211048_info.csv') as f:
        lines = f.readlines()
        for i, line in enumerate(lines[:10], 1):
            print(f"Line {i}: {line.decode('utf-8').strip()}")
# utf-8 decode turn it from byte string to normal string, as we have different number of columns in some of the rows

Line 1: version,2.1.0
Line 2: info,balls_per_over,6
Line 3: info,team,New Zealand
Line 4: info,team,Australia
Line 5: info,gender,male
Line 6: info,season,2004/05
Line 7: info,date,2005/02/17
Line 8: info,venue,Eden Park
Line 9: info,city,Auckland
Line 10: info,toss_winner,Australia


Want to only include games between Eng and Aus

The info files contain what teams are playing

In [6]:
it20s_info_files = [f for f in it20s_namelist if f.endswith('_info.csv')]
# using [] to create a list of every file in the filelist that ends in _info.csv
print(len(it20s_info_files))

2620


Half the files have _info at the end which is what we want. Also -1 for the README file

In [7]:
eng_vs_aus_matches = []

with zipfile.ZipFile('t20s_male_csv2.zip', 'r') as all_it20s:
    for f in it20s_info_files:
        with all_it20s.open(f) as file:
            lines = file.readlines()
            line3 = lines[2].decode('utf-8')
            line4 = lines[3].decode('utf-8')
            # lines 2 and 3 actually 3 and 4 with 0 index
            # decode each line from byte to string

            if "England" in line3 and "Australia" in line4 or \
               "Australia" in line3 and "England" in line4:# check both orders aus/eng and eng/aus
                eng_vs_aus_matches.append(f)
# gives list with info docs that are between eng and aus

In [8]:
print(len(eng_vs_aus_matches))

26


In [9]:
match_ids = [f.replace('_info.csv', '') for f in eng_vs_aus_matches]
print(match_ids)
# gives me all the match ids for t20Is between E and A, now need to make a file with these in

['211028', '249227', '287861', '350050', '412703', '446960', '446961', '566937', '566938', '636164', '636165', '636166', '743975', '1072317', '1072318', '1119542', '1198235', '1198236', '1198237', '1273737', '1317486', '1317487', '1317488', '1415717', '1385697', '1385698']


In [10]:
files_to_include = []
for mid in match_ids:
  files_to_include.append(f"{mid}.csv")
  files_to_include.append(f"{mid}_info.csv")

#use f string to insert

In [11]:
source_zip = 't20s_male_csv2.zip'
output_zip = 'eng_aus_matches_only.zip'

with zipfile.ZipFile(source_zip, 'r') as zin:
    with zipfile.ZipFile(output_zip, 'w') as zout:
        for f in files_to_include:
            data = zin.read(f)
            zout.writestr(f, data)


In [12]:
with zipfile.ZipFile("eng_aus_matches_only.zip", "r") as zip_ref:
    zip_ref.printdir()
# list the files in the zip

File Name                                             Modified             Size
211028.csv                                     2025-08-15 10:07:46        23981
211028_info.csv                                2025-08-15 10:07:46         2161
249227.csv                                     2025-08-15 10:07:46        29907
249227_info.csv                                2025-08-15 10:07:46         2232
287861.csv                                     2025-08-15 10:07:46        22655
287861_info.csv                                2025-08-15 10:07:46         2268
350050.csv                                     2025-08-15 10:07:46        14547
350050_info.csv                                2025-08-15 10:07:46         2223
412703.csv                                     2025-08-15 10:07:46        28866
412703_info.csv                                2025-08-15 10:07:46         2273
446960.csv                                     2025-08-15 10:07:46        26808
446960_info.csv                         

# **Intial Feature Engineering**


1.   These features arer going to be very basic and got from the existing CSV
2.   The initial df for one match id




When setting up ypu dataframe to be suitable for the TFT model I need a

1.   Group ID, to identify each independent sequence = .ID
2.   Time index, to provide temporal structure to each independent sequence = .TIME
3.   Features: These can be Static variables, past variables, future known variables
4.   Target Variable coulumns, what I am trying to predict  .TARGET










In [13]:
with zipfile.ZipFile("eng_aus_matches_only.zip", "r") as zip_ref:
    with zip_ref.open("211028.csv") as file:
        df_2011028 = pd.read_csv(file)
# taking one eng aus game and converting the ball by ball csv into a pd df

In [14]:
df_2011028.head(5)

match_id  season  start_date          venue  innings  ball batting_team  \
0    211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1    211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2    211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3    211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4    211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   

  bowling_team         striker     non_striker  ... extras  wides  noballs  \
0    Australia  ME Trescothick        GO Jones  ...      0    NaN      NaN   
1    Australia  ME Trescothick        GO Jones  ...      0    NaN      NaN   
2    Australia        GO Jones  ME Trescothick  ...      0    NaN      NaN   
3    Australia        GO Jones  ME Trescothick  ...      0    NaN      NaN   
4    Australia        GO Jones  ME Trescothick  ...      0    NaN      NaN   

   byes  legbyes  penalty  wicket_type  player_dismissed other_wicket_type  \
0   NaN      NaN      NaN          NaN               NaN               NaN   
1   NaN      NaN      NaN          NaN               NaN               NaN   
2   NaN      NaN      NaN          NaN               NaN               NaN   
3   NaN      NaN      NaN          NaN               NaN               NaN   
4   NaN      NaN      NaN          NaN               NaN               NaN   

  other_player_dismissed  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  

[5 rows x 22 columns]

Add **group ID** for TFT model

In [15]:
# add match id and innings column as TFT expects a group id to identify independent sequences, each innings is different even if they are same match
df_2011028['match_id_innings'] = df_2011028['match_id'].astype(str)+'_'+df_2011028['innings'].astype(str)

df_2011028.head(1)

match_id  season  start_date          venue  innings  ball batting_team  \
0    211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   

  bowling_team         striker non_striker  ... wides  noballs  byes  legbyes  \
0    Australia  ME Trescothick    GO Jones  ...   NaN      NaN   NaN      NaN   

   penalty  wicket_type  player_dismissed  other_wicket_type  \
0      NaN          NaN               NaN                NaN   

  other_player_dismissed match_id_innings  
0                    NaN         211028_1  

[1 rows x 23 columns]

Add **time index** for TFT model

In [16]:
df_2011028['time_idx'] = df_2011028.groupby('match_id_innings').cumcount() + 1

df_2011028.head(10)

match_id  season  start_date          venue  innings  ball batting_team  \
0    211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1    211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2    211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3    211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4    211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   
5    211028    2005  2005-06-13  The Rose Bowl        1   0.6      England   
6    211028    2005  2005-06-13  The Rose Bowl        1   0.7      England   
7    211028    2005  2005-06-13  The Rose Bowl        1   1.1      England   
8    211028    2005  2005-06-13  The Rose Bowl        1   1.2      England   
9    211028    2005  2005-06-13  The Rose Bowl        1   1.3      England   

  bowling_team         striker     non_striker  ... noballs  byes  legbyes  \
0    Australia  ME Trescothick        GO Jones  ...     NaN   NaN      NaN   
1    Australia  ME Trescothick        GO Jones  ...     NaN   NaN      NaN   
2    Australia        GO Jones  ME Trescothick  ...     NaN   NaN      NaN   
3    Australia        GO Jones  ME Trescothick  ...     NaN   NaN      NaN   
4    Australia        GO Jones  ME Trescothick  ...     NaN   NaN      NaN   
5    Australia        GO Jones  ME Trescothick  ...     1.0   NaN      NaN   
6    Australia        GO Jones  ME Trescothick  ...     NaN   NaN      NaN   
7    Australia  ME Trescothick        GO Jones  ...     NaN   NaN      NaN   
8    Australia  ME Trescothick        GO Jones  ...     NaN   NaN      NaN   
9    Australia  ME Trescothick        GO Jones  ...     NaN   NaN      NaN   

   penalty  wicket_type  player_dismissed  other_wicket_type  \
0      NaN          NaN               NaN                NaN   
1      NaN          NaN               NaN                NaN   
2      NaN          NaN               NaN                NaN   
3      NaN          NaN               NaN                NaN   
4      NaN          NaN               NaN                NaN   
5      NaN          NaN               NaN                NaN   
6      NaN          NaN               NaN                NaN   
7      NaN          NaN               NaN                NaN   
8      NaN          NaN               NaN                NaN   
9      NaN          NaN               NaN                NaN   

   other_player_dismissed match_id_innings time_idx  
0                     NaN         211028_1        1  
1                     NaN         211028_1        2  
2                     NaN         211028_1        3  
3                     NaN         211028_1        4  
4                     NaN         211028_1        5  
5                     NaN         211028_1        6  
6                     NaN         211028_1        7  
7                     NaN         211028_1        8  
8                     NaN         211028_1        9  
9                     NaN         211028_1       10  

[10 rows x 24 columns]

Add total_runs as a simple Target Variable

In [17]:
df_2011028['total_runs_off_ball'] = df_2011028['runs_off_bat'].astype(int) + df_2011028['extras'].astype(int)
df_2011028.head(5)

match_id  season  start_date          venue  innings  ball batting_team  \
0    211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1    211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2    211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3    211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4    211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   

  bowling_team         striker     non_striker  ... byes  legbyes  penalty  \
0    Australia  ME Trescothick        GO Jones  ...  NaN      NaN      NaN   
1    Australia  ME Trescothick        GO Jones  ...  NaN      NaN      NaN   
2    Australia        GO Jones  ME Trescothick  ...  NaN      NaN      NaN   
3    Australia        GO Jones  ME Trescothick  ...  NaN      NaN      NaN   
4    Australia        GO Jones  ME Trescothick  ...  NaN      NaN      NaN   

   wicket_type  player_dismissed  other_wicket_type  other_player_dismissed  \
0          NaN               NaN                NaN                     NaN   
1          NaN               NaN                NaN                     NaN   
2          NaN               NaN                NaN                     NaN   
3          NaN               NaN                NaN                     NaN   
4          NaN               NaN                NaN                     NaN   

   match_id_innings time_idx total_runs_off_ball  
0          211028_1        1                   0  
1          211028_1        2                   1  
2          211028_1        3                   0  
3          211028_1        4                   0  
4          211028_1        5                   0  

[5 rows x 25 columns]

Add cumulative runs

In [18]:
df_2011028['cum_runs'] = df_2011028.groupby('match_id_innings')['total_runs_off_ball'].cumsum()
df_2011028.head(15)

match_id  season  start_date          venue  innings  ball batting_team  \
0     211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1     211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2     211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3     211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4     211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   
5     211028    2005  2005-06-13  The Rose Bowl        1   0.6      England   
6     211028    2005  2005-06-13  The Rose Bowl        1   0.7      England   
7     211028    2005  2005-06-13  The Rose Bowl        1   1.1      England   
8     211028    2005  2005-06-13  The Rose Bowl        1   1.2      England   
9     211028    2005  2005-06-13  The Rose Bowl        1   1.3      England   
10    211028    2005  2005-06-13  The Rose Bowl        1   1.4      England   
11    211028    2005  2005-06-13  The Rose Bowl        1   1.5      England   
12    211028    2005  2005-06-13  The Rose Bowl        1   1.6      England   
13    211028    2005  2005-06-13  The Rose Bowl        1   1.7      England   
14    211028    2005  2005-06-13  The Rose Bowl        1   2.1      England   

   bowling_team         striker     non_striker  ... legbyes  penalty  \
0     Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
1     Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
2     Australia        GO Jones  ME Trescothick  ...     NaN      NaN   
3     Australia        GO Jones  ME Trescothick  ...     NaN      NaN   
4     Australia        GO Jones  ME Trescothick  ...     NaN      NaN   
5     Australia        GO Jones  ME Trescothick  ...     NaN      NaN   
6     Australia        GO Jones  ME Trescothick  ...     NaN      NaN   
7     Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
8     Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
9     Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
10    Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
11    Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
12    Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
13    Australia  ME Trescothick        GO Jones  ...     NaN      NaN   
14    Australia  ME Trescothick        GO Jones  ...     NaN      NaN   

    wicket_type  player_dismissed  other_wicket_type  other_player_dismissed  \
0           NaN               NaN                NaN                     NaN   
1           NaN               NaN                NaN                     NaN   
2           NaN               NaN                NaN                     NaN   
3           NaN               NaN                NaN                     NaN   
4           NaN               NaN                NaN                     NaN   
5           NaN               NaN                NaN                     NaN   
6           NaN               NaN                NaN                     NaN   
7           NaN               NaN                NaN                     NaN   
8           NaN               NaN                NaN                     NaN   
9           NaN               NaN                NaN                     NaN   
10          NaN               NaN                NaN                     NaN   
11          NaN               NaN                NaN                     NaN   
12          NaN               NaN                NaN                     NaN   
13          NaN               NaN                NaN                     NaN   
14          NaN               NaN                NaN                     NaN   

    match_id_innings  time_idx total_runs_off_ball cum_runs  
0           211028_1         1                   0        0  
1           211028_1         2                   1        1  
2           211028_1         3                   0        1  
3           211028_1         4           

Add cumulative wickets

In [19]:
df_2011028['is_wicket'] = df_2011028['wicket_type'].notna().astype(int)
# not na, check if there is a nan value or something else, then as type turns to integer rather than t/f
df_2011028['cum_wickets'] = df_2011028.groupby('match_id_innings')['is_wicket'].cumsum()
# can now count number of wickets
df_2011028.head(100)

match_id  season  start_date          venue  innings  ball batting_team  \
0     211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1     211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2     211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3     211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4     211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   
..       ...     ...         ...            ...      ...   ...          ...   
95    211028    2005  2005-06-13  The Rose Bowl        1  15.2      England   
96    211028    2005  2005-06-13  The Rose Bowl        1  15.3      England   
97    211028    2005  2005-06-13  The Rose Bowl        1  15.4      England   
98    211028    2005  2005-06-13  The Rose Bowl        1  15.5      England   
99    211028    2005  2005-06-13  The Rose Bowl        1  15.6      England   

   bowling_team         striker     non_striker  ... wicket_type  \
0     Australia  ME Trescothick        GO Jones  ...         NaN   
1     Australia  ME Trescothick        GO Jones  ...         NaN   
2     Australia        GO Jones  ME Trescothick  ...         NaN   
3     Australia        GO Jones  ME Trescothick  ...         NaN   
4     Australia        GO Jones  ME Trescothick  ...         NaN   
..          ...             ...             ...  ...         ...   
95    Australia  PD Collingwood      AJ Strauss  ...         NaN   
96    Australia      AJ Strauss  PD Collingwood  ...         NaN   
97    Australia      AJ Strauss  PD Collingwood  ...         NaN   
98    Australia  PD Collingwood      AJ Strauss  ...         NaN   
99    Australia  PD Collingwood      AJ Strauss  ...         NaN   

    player_dismissed  other_wicket_type  other_player_dismissed  \
0                NaN                NaN                     NaN   
1                NaN                NaN                     NaN   
2                NaN                NaN                     NaN   
3                NaN                NaN                     NaN   
4                NaN                NaN                     NaN   
..               ...                ...                     ...   
95               NaN                NaN                     NaN   
96               NaN                NaN                     NaN   
97               NaN                NaN                     NaN   
98               NaN                NaN                     NaN   
99               NaN                NaN                     NaN   

    match_id_innings  time_idx  total_runs_off_ball  cum_runs is_wicket  \
0           211028_1         1                    0         0         0   
1           211028_1         2                    1         1         0   
2           211028_1         3                    0         1         0   
3           211028_1         4                    0         1         0   
4           211028_1         5                    0         1         0   
..               ...       ...                  ...       ...       ...   
95          211028_1        96                    1       126         0   
96          211028_1        97                    0       126         0   
97          211028_1        98                    1       127         0   
98          211028_1        99                    4       131         0   
99          211028_1       100                    1       132         0   

   cum_wickets  
0            0  
1            0  
2            0  
3            0  
4            0  
..         ...  
95           5  
96           5  
97           5  
98           5  
99           5  

[100 rows x 28 columns]

Add lagged feature that shows runs from the previous 3 balls

In [20]:
df_2011028['runs_prev_3']=df_2011028.groupby('match_id')['total_runs_off_ball'].shift(3)
# use shift to fidn the total of the last 3 balls
df_2011028['runs_prev_3'] = df_2011028['runs_prev_3'].fillna(0).astype(int)
# was originally returning a float as there was nan values for the first 3 balls. However, I have set it to zero. This is because this feature is to give an idea of momentum and at start of the innings there is little momentum so zero will have low impact. Also as we have time_idx the model woll recognise these balls as being early in the innings.
df_2011028.head(15)

match_id  season  start_date          venue  innings  ball batting_team  \
0     211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1     211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2     211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3     211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4     211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   
5     211028    2005  2005-06-13  The Rose Bowl        1   0.6      England   
6     211028    2005  2005-06-13  The Rose Bowl        1   0.7      England   
7     211028    2005  2005-06-13  The Rose Bowl        1   1.1      England   
8     211028    2005  2005-06-13  The Rose Bowl        1   1.2      England   
9     211028    2005  2005-06-13  The Rose Bowl        1   1.3      England   
10    211028    2005  2005-06-13  The Rose Bowl        1   1.4      England   
11    211028    2005  2005-06-13  The Rose Bowl        1   1.5      England   
12    211028    2005  2005-06-13  The Rose Bowl        1   1.6      England   
13    211028    2005  2005-06-13  The Rose Bowl        1   1.7      England   
14    211028    2005  2005-06-13  The Rose Bowl        1   2.1      England   

   bowling_team         striker     non_striker  ... player_dismissed  \
0     Australia  ME Trescothick        GO Jones  ...              NaN   
1     Australia  ME Trescothick        GO Jones  ...              NaN   
2     Australia        GO Jones  ME Trescothick  ...              NaN   
3     Australia        GO Jones  ME Trescothick  ...              NaN   
4     Australia        GO Jones  ME Trescothick  ...              NaN   
5     Australia        GO Jones  ME Trescothick  ...              NaN   
6     Australia        GO Jones  ME Trescothick  ...              NaN   
7     Australia  ME Trescothick        GO Jones  ...              NaN   
8     Australia  ME Trescothick        GO Jones  ...              NaN   
9     Australia  ME Trescothick        GO Jones  ...              NaN   
10    Australia  ME Trescothick        GO Jones  ...              NaN   
11    Australia  ME Trescothick        GO Jones  ...              NaN   
12    Australia  ME Trescothick        GO Jones  ...              NaN   
13    Australia  ME Trescothick        GO Jones  ...              NaN   
14    Australia  ME Trescothick        GO Jones  ...              NaN   

    other_wicket_type  other_player_dismissed  match_id_innings  time_idx  \
0                 NaN                     NaN          211028_1         1   
1                 NaN                     NaN          211028_1         2   
2                 NaN                     NaN          211028_1         3   
3                 NaN                     NaN          211028_1         4   
4                 NaN                     NaN          211028_1         5   
5                 NaN                     NaN          211028_1         6   
6                 NaN                     NaN          211028_1         7   
7                 NaN                     NaN          211028_1         8   
8                 NaN                     NaN          211028_1         9   
9                 NaN                     NaN          211028_1        10   
10                NaN                     NaN          211028_1        11   
11                NaN                     NaN          211028_1        12   
12                NaN                     NaN          211028_1        13   
13                NaN                     NaN          211028_1        14   
14                NaN                     NaN          211028_1        15   

    total_runs_off_ball  cum_runs  is_wicket cum_wickets runs_prev_3  
0                     0         0          0           0           0  
1                     1         1          0           0           0  
2                     0         1          0           0           0  
3                     0         1          0         

Create over number so we can do powerplay and death overs

In [21]:
df_2011028['over_number'] = df_2011028['ball'].apply(lambda x: int(x) + 1)
df_2011028.head(146)
# look at 146 as there was an over with a noball and was checking that it work even if there was more than 6 balls in the over and it did.

match_id  season  start_date          venue  innings  ball batting_team  \
0      211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1      211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2      211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3      211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4      211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   
..        ...     ...         ...            ...      ...   ...          ...   
141    211028    2005  2005-06-13  The Rose Bowl        2   2.5    Australia   
142    211028    2005  2005-06-13  The Rose Bowl        2   2.6    Australia   
143    211028    2005  2005-06-13  The Rose Bowl        2   2.7    Australia   
144    211028    2005  2005-06-13  The Rose Bowl        2   3.1    Australia   
145    211028    2005  2005-06-13  The Rose Bowl        2   3.2    Australia   

    bowling_team         striker     non_striker  ... other_wicket_type  \
0      Australia  ME Trescothick        GO Jones  ...               NaN   
1      Australia  ME Trescothick        GO Jones  ...               NaN   
2      Australia        GO Jones  ME Trescothick  ...               NaN   
3      Australia        GO Jones  ME Trescothick  ...               NaN   
4      Australia        GO Jones  ME Trescothick  ...               NaN   
..           ...             ...             ...  ...               ...   
141      England    AC Gilchrist       ML Hayden  ...               NaN   
142      England       ML Hayden       A Symonds  ...               NaN   
143      England       A Symonds       MJ Clarke  ...               NaN   
144      England       MJ Clarke       A Symonds  ...               NaN   
145      England      MEK Hussey       A Symonds  ...               NaN   

     other_player_dismissed  match_id_innings  time_idx  total_runs_off_ball  \
0                       NaN          211028_1         1                    0   
1                       NaN          211028_1         2                    1   
2                       NaN          211028_1         3                    0   
3                       NaN          211028_1         4                    0   
4                       NaN          211028_1         5                    0   
..                      ...               ...       ...                  ...   
141                     NaN          211028_2        17                    0   
142                     NaN          211028_2        18                    0   
143                     NaN          211028_2        19                    0   
144                     NaN          211028_2        20                    0   
145                     NaN          211028_2        21                    0   

     cum_runs  is_wicket  cum_wickets runs_prev_3 over_number  
0           0          0            0           0           1  
1           1          0            0           0           1  
2           1          0            0           0           1  
3           1          0            0           0           1  
4           1          0            0           1           1  
..        ...        ...          ...         ...         ...  
141        23          1            1           1           3  
142        23          1            2           1           3  
143        23          0            2           2           3  
144        23          1            3           0           4  
145        23          0            3           0           4  

[146 rows x 30 columns]

In [22]:
#powerplayer <= 6 and death overs >= 17
df_2011028['powerplay']=(df_2011028['over_number']<=6).astype(int)
df_2011028['death_overs']=(df_2011028['over_number']>=17).astype(int)
df_2011028.head(120)

# during the powerplay teams are only allowed 2 fielders outside of the 30 yard circle
# for the remaining overs you are not allowed more than 5 fielders outside the ring
# the last 4 overs are considered the death overs and bowling style is known to change, bowlers tend to try variations i.e slower balls to prevent batsmen scoring

match_id  season  start_date          venue  innings  ball batting_team  \
0      211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1      211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2      211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3      211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4      211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   
..        ...     ...         ...            ...      ...   ...          ...   
115    211028    2005  2005-06-13  The Rose Bowl        1  18.3      England   
116    211028    2005  2005-06-13  The Rose Bowl        1  18.4      England   
117    211028    2005  2005-06-13  The Rose Bowl        1  18.5      England   
118    211028    2005  2005-06-13  The Rose Bowl        1  18.6      England   
119    211028    2005  2005-06-13  The Rose Bowl        1  19.1      England   

    bowling_team         striker     non_striker  ... match_id_innings  \
0      Australia  ME Trescothick        GO Jones  ...         211028_1   
1      Australia  ME Trescothick        GO Jones  ...         211028_1   
2      Australia        GO Jones  ME Trescothick  ...         211028_1   
3      Australia        GO Jones  ME Trescothick  ...         211028_1   
4      Australia        GO Jones  ME Trescothick  ...         211028_1   
..           ...             ...             ...  ...              ...   
115    Australia      VS Solanki  PD Collingwood  ...         211028_1   
116    Australia  PD Collingwood      VS Solanki  ...         211028_1   
117    Australia  PD Collingwood      VS Solanki  ...         211028_1   
118    Australia  PD Collingwood      VS Solanki  ...         211028_1   
119    Australia      VS Solanki  PD Collingwood  ...         211028_1   

     time_idx  total_runs_off_ball  cum_runs  is_wicket  cum_wickets  \
0           1                    0         0          0            0   
1           2                    1         1          0            0   
2           3                    0         1          0            0   
3           4                    0         1          0            0   
4           5                    0         1          0            0   
..        ...                  ...       ...        ...          ...   
115       116                    1       159          0            6   
116       117                    0       159          0            6   
117       118                    4       163          0            6   
118       119                    4       167          0            6   
119       120                    2       169          0            6   

     runs_prev_3  over_number powerplay death_overs  
0              0            1         1           0  
1              0            1         1           0  
2              0            1         1           0  
3              0            1         1           0  
4              1            1         1           0  
..           ...          ...       ...         ...  
115            1           19         0           1  
116            1           19         0           1  
117            0           19         0           1  
118            1           19         0           1  
119            0           20         0           1  

[120 rows x 32 columns]

Add some static features from the info file
1. doing this basically now, will need to make a mother file with all info and link stuff we want to match_id

In [23]:
info_dict_2011028 = {}

with zipfile.ZipFile("eng_aus_matches_only.zip", "r") as zip_ref:
    with zip_ref.open("211028_info.csv") as f:
        for line in f:
            parts = line.decode('utf-8').strip().split(",")
            if len(parts) == 3 and parts[0] == "info":
                key = parts[1].strip()
                value = parts[2].strip()
                info_dict_2011028[key] = value

# create empty dict and then we can add key value pairs with the information I want

In [24]:
#set what we want
for key in ['city', 'toss_winner', 'toss_decision']:
  df_2011028[key] = info_dict_2011028[key]
  df_2011028.head(5)

In [25]:
pd.set_option('display.max_columns', None)
df_2011028.head()


match_id  season  start_date          venue  innings  ball batting_team  \
0    211028    2005  2005-06-13  The Rose Bowl        1   0.1      England   
1    211028    2005  2005-06-13  The Rose Bowl        1   0.2      England   
2    211028    2005  2005-06-13  The Rose Bowl        1   0.3      England   
3    211028    2005  2005-06-13  The Rose Bowl        1   0.4      England   
4    211028    2005  2005-06-13  The Rose Bowl        1   0.5      England   

  bowling_team         striker     non_striker bowler  runs_off_bat  extras  \
0    Australia  ME Trescothick        GO Jones  B Lee             0       0   
1    Australia  ME Trescothick        GO Jones  B Lee             1       0   
2    Australia        GO Jones  ME Trescothick  B Lee             0       0   
3    Australia        GO Jones  ME Trescothick  B Lee             0       0   
4    Australia        GO Jones  ME Trescothick  B Lee             0       0   

   wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  \
0    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
1    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
2    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
3    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
4    NaN      NaN   NaN      NaN      NaN         NaN              NaN   

   other_wicket_type  other_player_dismissed match_id_innings  time_idx  \
0                NaN                     NaN         211028_1         1   
1                NaN                     NaN         211028_1         2   
2                NaN                     NaN         211028_1         3   
3                NaN                     NaN         211028_1         4   
4                NaN                     NaN         211028_1         5   

   total_runs_off_ball  cum_runs  is_wicket  cum_wickets  runs_prev_3  \
0                    0         0          0            0            0   
1                    1         1          0            0            0   
2                    0         1          0            0            0   
3                    0         1          0            0            0   
4                    0         1          0            0            1   

   over_number  powerplay  death_overs         city toss_winner toss_decision  
0            1          1            0  Southampton     England           bat  
1            1          1            0  Southampton     England           bat  
2            1          1            0  Southampton     England           bat  
3            1          1            0  Southampton     England           bat  
4            1          1            0  Southampton     England           bat

# **Eng/Aus Pipeline**

### Input features

Now add all those features I've added to a dataframe for all the eng and aus matches

In [26]:
# function tp add all the features i have already created
def process_match(ball_df, info_dict):
    df = ball_df.copy()

    # match_id_innings
    df['match_id_innings'] = df['match_id'].astype(str) + "_" + df['innings'].astype(str)
    # time_idx
    df['time_idx'] = df.groupby('match_id_innings').cumcount() + 1
    # Total runs off ball
    df['total_runs_off_ball'] = df['runs_off_bat'] + df['extras']
    # Cumulative runs
    df['cum_runs'] = df.groupby('match_id_innings')['total_runs_off_ball'].cumsum()
    # wickets
    df['is_wicket'] = df['wicket_type'].notna().astype(int)
    df['cum_wickets'] = df.groupby('match_id_innings')['is_wicket'].cumsum()
    # previous 3 balls
    df['runs_prev_3'] = df.groupby('match_id_innings')['total_runs_off_ball'].shift(3).fillna(0).astype(int)
    # Over number
    df['over_number'] = df['ball'].apply(lambda x: int(x) + 1)
    # Powerplay and death overs
    df['powerplay'] = (df['over_number'] <= 6).astype(int)
    df['death_overs'] = (df['over_number'] >= 17).astype(int)

    # Balls remaing
    #legal delivery column, cum count it then subtract from 120
    df['legal_delivery'] = ((df['wides'].fillna(0) == 0) & (df['noballs'].fillna(0) == 0)).astype(int)
    df['legal_delivery_number'] = df.groupby('match_id_innings')['legal_delivery'].cumsum()
    df['balls_remaining'] = 120 - df['legal_delivery_number']


    # Static covariates from info file
    for key in ['city', 'toss_winner', 'toss_decision']:
        df[key] = info_dict.get(key, None)


    return df



In [27]:
zip_path = "eng_aus_matches_only.zip"

all_eng_aus_matches = []

# Open the zip file
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    for match_id in match_ids:
        ball_file = f"{match_id}.csv"
        info_file = f"{match_id}_info.csv"

        with zip_ref.open(ball_file) as f:
            ball_df = pd.read_csv(f)
            # look at the ball by ball file

        info_dict = {}
        with zip_ref.open(info_file) as f:
            for line in f:
                parts = line.decode('utf-8').strip().split(",")
                if len(parts) == 3 and parts[0] == "info":
                    key = parts[1].strip()
                    value = parts[2].strip()
                    info_dict[key] = value
                    # parse the info file for static covariates

        processed_df = process_match(ball_df, info_dict)
        all_eng_aus_matches.append(processed_df)

df_all_eng_aus = pd.concat(all_eng_aus_matches, ignore_index=True)

df_all_eng_aus.head(127)


match_id season  start_date          venue  innings  ball batting_team  \
0      211028   2005  2005-06-13  The Rose Bowl        1   0.1      England   
1      211028   2005  2005-06-13  The Rose Bowl        1   0.2      England   
2      211028   2005  2005-06-13  The Rose Bowl        1   0.3      England   
3      211028   2005  2005-06-13  The Rose Bowl        1   0.4      England   
4      211028   2005  2005-06-13  The Rose Bowl        1   0.5      England   
..        ...    ...         ...            ...      ...   ...          ...   
122    211028   2005  2005-06-13  The Rose Bowl        1  19.4      England   
123    211028   2005  2005-06-13  The Rose Bowl        1  19.5      England   
124    211028   2005  2005-06-13  The Rose Bowl        1  19.6      England   
125    211028   2005  2005-06-13  The Rose Bowl        2   0.1    Australia   
126    211028   2005  2005-06-13  The Rose Bowl        2   0.2    Australia   

    bowling_team         striker     non_striker      bowler  runs_off_bat  \
0      Australia  ME Trescothick        GO Jones       B Lee             0   
1      Australia  ME Trescothick        GO Jones       B Lee             1   
2      Australia        GO Jones  ME Trescothick       B Lee             0   
3      Australia        GO Jones  ME Trescothick       B Lee             0   
4      Australia        GO Jones  ME Trescothick       B Lee             0   
..           ...             ...             ...         ...           ...   
122    Australia      VS Solanki  PD Collingwood  GD McGrath             0   
123    Australia  PD Collingwood         J Lewis  GD McGrath             4   
124    Australia  PD Collingwood         J Lewis  GD McGrath             0   
125      England    AC Gilchrist       ML Hayden     D Gough             0   
126      England    AC Gilchrist       ML Hayden     D Gough             4   

     extras  wides  noballs  byes  legbyes  penalty wicket_type  \
0         0    NaN      NaN   NaN      NaN      NaN         NaN   
1         0    NaN      NaN   NaN      NaN      NaN         NaN   
2         0    NaN      NaN   NaN      NaN      NaN         NaN   
3         0    NaN      NaN   NaN      NaN      NaN         NaN   
4         0    NaN      NaN   NaN      NaN      NaN         NaN   
..      ...    ...      ...   ...      ...      ...         ...   
122       0    NaN      NaN   NaN      NaN      NaN      caught   
123       0    NaN      NaN   NaN      NaN      NaN         NaN   
124       0    NaN      NaN   NaN      NaN      NaN      caught   
125       0    NaN      NaN   NaN      NaN      NaN         NaN   
126       0    NaN      NaN   NaN      NaN      NaN         NaN   

    player_dismissed  other_wicket_type  other_player_dismissed  \
0                NaN                NaN                     NaN   
1                NaN                NaN                     NaN   
2                NaN                NaN                     NaN   
3                NaN                NaN                     NaN   
4                NaN                NaN                     NaN   
..               ...                ...                     ...   
122       VS Solanki                NaN                     NaN   
123              NaN                NaN                     NaN   
124   PD Collingwood                NaN                     NaN   
125              NaN                NaN                     NaN   
126              NaN                NaN                     NaN   

    match_id_innings  time_idx  total_runs_off_ball  cum_runs  is_wicket  \
0           211028_1         1                    0         0          0   
1           211028_1         2                    1         1          0   
2           211028_1         3                    0         1          0   
3           211028_1         4                    0         1          0   
4           211028_1         5                    0         1          0   
..               ...       ...                  ...  

Lets do some idiot checks!

In [28]:
#number of unique match ids, there should be 26...
df_all_eng_aus['match_id'].nunique()

# lets go

26

In [29]:
# balls per match
df_all_eng_aus['match_id'].value_counts()

#all look about right, the shorter games are due to match abadonment and domination

match_id
1317486    255
1317487    254
636164     251
1415717    251
566937     250
566938     249
249227     249
1198235    248
743975     246
446961     245
1119542    245
1385697    245
446960     244
1385698    244
1198237    243
1198236    239
1072317    238
412703     231
636166     230
1072318    218
211028     215
636165     214
287861     212
1273737    197
350050     136
1317488    100
Name: count, dtype: int64

In [30]:
df_all_eng_aus[df_all_eng_aus['match_id'] == 350050].head()


match_id season  start_date         venue  innings  ball batting_team  \
676    350050   2009  2009-08-30  Old Trafford        1   0.1    Australia   
677    350050   2009  2009-08-30  Old Trafford        1   0.2    Australia   
678    350050   2009  2009-08-30  Old Trafford        1   0.3    Australia   
679    350050   2009  2009-08-30  Old Trafford        1   0.4    Australia   
680    350050   2009  2009-08-30  Old Trafford        1   0.5    Australia   

    bowling_team    striker non_striker       bowler  runs_off_bat  extras  \
676      England  SR Watson   DA Warner  JM Anderson             0       0   
677      England  SR Watson   DA Warner  JM Anderson             1       0   
678      England  DA Warner   SR Watson  JM Anderson             2       0   
679      England  DA Warner   SR Watson  JM Anderson             0       0   
680      England  DA Warner   SR Watson  JM Anderson             0       1   

     wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  \
676    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
677    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
678    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
679    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
680    1.0      NaN   NaN      NaN      NaN         NaN              NaN   

     other_wicket_type  other_player_dismissed match_id_innings  time_idx  \
676                NaN                     NaN         350050_1         1   
677                NaN                     NaN         350050_1         2   
678                NaN                     NaN         350050_1         3   
679                NaN                     NaN         350050_1         4   
680                NaN                     NaN         350050_1         5   

     total_runs_off_ball  cum_runs  is_wicket  cum_wickets  runs_prev_3  \
676                    0         0          0            0            0   
677                    1         1          0            0            0   
678                    2         3          0            0            0   
679                    0         3          0            0            0   
680                    1         4          0            0            1   

     over_number  powerplay  death_overs  legal_delivery  \
676            1          1            0               1   
677            1          1            0               1   
678            1          1            0               1   
679            1          1            0               1   
680            1          1            0               0   

     legal_delivery_number  balls_remaining        city toss_winner  \
676                      1              119  Manchester     England   
677                      2              118  Manchester     England   
678                      3              117  Manchester     England   
679                      4              116  Manchester     England   
680                      4              116  Manchester     England   

    toss_decision  
676         field  
677         field  
678         field  
679         field  
680         field

In [31]:
df_all_eng_aus[df_all_eng_aus['match_id_innings'] == '211028_1'][['time_idx', 'ball', 'legal_delivery', 'legal_delivery_number', 'balls_remaining']].tail(10)
# looks like balls_remaining works

time_idx  ball  legal_delivery  legal_delivery_number  balls_remaining
115       116  18.3               1                    111                9
116       117  18.4               1                    112                8
117       118  18.5               1                    113                7
118       119  18.6               1                    114                6
119       120  19.1               1                    115                5
120       121  19.2               1                    116                4
121       122  19.3               1                    117                3
122       123  19.4               1                    118                2
123       124  19.5               1                    119                1
124       125  19.6               1                    120                0

### Target Variables
Add target variables to the process match function

In [32]:
# function tp add all the features i have already created
def process_match(ball_df, info_dict):
    df = ball_df.copy()

    # match_id_innings
    df['match_id_innings'] = df['match_id'].astype(str) + "_" + df['innings'].astype(str)
    # time_idx
    df['time_idx'] = df.groupby('match_id_innings').cumcount() + 1
    # Total runs off ball
    df['total_runs_off_ball'] = df['runs_off_bat'] + df['extras']
    # Cumulative runs
    df['cum_runs'] = df.groupby('match_id_innings')['total_runs_off_ball'].cumsum()
    # wickets
    df['is_wicket'] = df['wicket_type'].notna().astype(int)
    df['cum_wickets'] = df.groupby('match_id_innings')['is_wicket'].cumsum()
    # previous 3 balls
    df['runs_prev_3'] = df.groupby('match_id_innings')['total_runs_off_ball'].shift(3).fillna(0).astype(int)
    # Over number
    df['over_number'] = df['ball'].apply(lambda x: int(x) + 1)
    # Powerplay and death overs
    df['powerplay'] = (df['over_number'] <= 6).astype(int)
    df['death_overs'] = (df['over_number'] >= 17).astype(int)

    # Static covariates from info file
    for key in ['city', 'toss_winner', 'toss_decision']:
        df[key] = info_dict.get(key, None)
    # Balls remaining
    #legal delivery column, cum count it then subtract from 120
    df['legal_delivery'] = ((df['wides'].fillna(0) == 0) & (df['noballs'].fillna(0) == 0)).astype(int)
    df['legal_delivery_number'] = df.groupby('match_id_innings')['legal_delivery'].cumsum()
    df['balls_remaining'] = 120 - df['legal_delivery_number']

    # add target variables
    # One-hot encoded runs
    for i in [0, 1, 2, 3, 4, 6]:
        df[f'rob_{i}'] = (df['runs_off_bat'] == i).astype(int)

    # Added this just so I have all target varibales together can delete is_wicket later
    df['wicket'] = df['is_wicket']

    # make extras binary not a value
    df['extra'] = (df['extras'] > 0).astype(int)

    # "Other" = not a given run, wicket, or extra. There is some wierd things that happen in cricketgames so I will have this as failsafe
    df['other'] = (
        (df[[f'rob_{i}' for i in [0,1,2,3,4,6]]].sum(axis=1) == 0) &
        (df['wicket'] == 0) &
        (df['extra'] == 0)
    ).astype(int)



    return df


Update df

In [33]:
zip_path = "eng_aus_matches_only.zip"

all_eng_aus_matches = []

# Open the zip file
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    for match_id in match_ids:
        ball_file = f"{match_id}.csv"
        info_file = f"{match_id}_info.csv"

        with zip_ref.open(ball_file) as f:
            ball_df = pd.read_csv(f)
            # look at the ball by ball file

        info_dict = {}
        with zip_ref.open(info_file) as f:
            for line in f:
                parts = line.decode('utf-8').strip().split(",")
                if len(parts) == 3 and parts[0] == "info":
                    key = parts[1].strip()
                    value = parts[2].strip()
                    info_dict[key] = value
                    # parse the info file for static covariates

        processed_df = process_match(ball_df, info_dict)
        all_eng_aus_matches.append(processed_df)

df_all_eng_aus = pd.concat(all_eng_aus_matches, ignore_index=True)

df_all_eng_aus.head()


match_id season  start_date          venue  innings  ball batting_team  \
0    211028   2005  2005-06-13  The Rose Bowl        1   0.1      England   
1    211028   2005  2005-06-13  The Rose Bowl        1   0.2      England   
2    211028   2005  2005-06-13  The Rose Bowl        1   0.3      England   
3    211028   2005  2005-06-13  The Rose Bowl        1   0.4      England   
4    211028   2005  2005-06-13  The Rose Bowl        1   0.5      England   

  bowling_team         striker     non_striker bowler  runs_off_bat  extras  \
0    Australia  ME Trescothick        GO Jones  B Lee             0       0   
1    Australia  ME Trescothick        GO Jones  B Lee             1       0   
2    Australia        GO Jones  ME Trescothick  B Lee             0       0   
3    Australia        GO Jones  ME Trescothick  B Lee             0       0   
4    Australia        GO Jones  ME Trescothick  B Lee             0       0   

   wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  \
0    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
1    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
2    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
3    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
4    NaN      NaN   NaN      NaN      NaN         NaN              NaN   

   other_wicket_type  other_player_dismissed match_id_innings  time_idx  \
0                NaN                     NaN         211028_1         1   
1                NaN                     NaN         211028_1         2   
2                NaN                     NaN         211028_1         3   
3                NaN                     NaN         211028_1         4   
4                NaN                     NaN         211028_1         5   

   total_runs_off_ball  cum_runs  is_wicket  cum_wickets  runs_prev_3  \
0                    0         0          0            0            0   
1                    1         1          0            0            0   
2                    0         1          0            0            0   
3                    0         1          0            0            0   
4                    0         1          0            0            1   

   over_number  powerplay  death_overs         city toss_winner toss_decision  \
0            1          1            0  Southampton     England           bat   
1            1          1            0  Southampton     England           bat   
2            1          1            0  Southampton     England           bat   
3            1          1            0  Southampton     England           bat   
4            1          1            0  Southampton     England           bat   

   legal_delivery  legal_delivery_number  balls_remaining  rob_0  rob_1  \
0               1                      1              119      1      0   
1               1                      2              118      0      1   
2               1                      3              117      1      0   
3               1                      4              116      1      0   
4               1                      5              115      1      0   

   rob_2  rob_3  rob_4  rob_6  wicket  extra  other  
0      0      0      0      0       0      0      0  
1      0      0      0      0       0      0      0  
2      0      0      0      0       0      0      0  
3      0      0      0      0       0      0      0  
4      0      0      0      0       0      0      0

In [34]:
# look how many instances there are of each one
df_all_eng_aus[['rob_0', 'rob_1', 'rob_2', 'rob_3', 'rob_4', 'rob_6', 'wicket', 'extra', 'other']].sum()


rob_0     2290
rob_1     2104
rob_2      501
rob_3       44
rob_4      702
rob_6      307
wicket     329
extra      315
other        1
dtype: int64

In [35]:
a = 2290+2104+501+44+702+307+329+315+1
print(a)

6593


In [36]:
len(df_all_eng_aus)

5949

The no. of istances and lentgh of df are different because some balls are runs of bat and extras i.e hit a four off a no-ball. Need to work out what I am going to do here.

In [37]:
df_all_eng_aus[df_all_eng_aus['other'] == 1]

# the one instance of other... travis head hit 5 off the bat!

# why is there 97 balls remaining when its delivery 3.6?
# must of been a wide/no-ball in the over... lets have a look

match_id season  start_date      venue  innings  ball batting_team  \
3574   1119542   2018  2018-06-27  Edgbaston        2   3.6    Australia   

     bowling_team  striker non_striker     bowler  runs_off_bat  extras  \
3574      England  TM Head    AJ Finch  CJ Jordan             5       0   

      wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  \
3574    NaN      NaN   NaN      NaN      NaN         NaN              NaN   

      other_wicket_type  other_player_dismissed match_id_innings  time_idx  \
3574                NaN                     NaN        1119542_2        25   

      total_runs_off_ball  cum_runs  is_wicket  cum_wickets  runs_prev_3  \
3574                    5        38          0            2            1   

      over_number  powerplay  death_overs        city toss_winner  \
3574            4          1            0  Birmingham   Australia   

     toss_decision  legal_delivery  legal_delivery_number  balls_remaining  \
3574         field               1                     23               97   

      rob_0  rob_1  rob_2  rob_3  rob_4  rob_6  wicket  extra  other  
3574      0      0      0      0      0      0       0      0      1

In [38]:
df_all_eng_aus[
    (df_all_eng_aus['match_id'] == 1119542) &
    (df_all_eng_aus['innings'] == 2) &
    (df_all_eng_aus['ball'].astype(str).str.startswith('3.'))
]
# yes ball 3 was a no ball

match_id season  start_date      venue  innings  ball batting_team  \
3569   1119542   2018  2018-06-27  Edgbaston        2   3.1    Australia   
3570   1119542   2018  2018-06-27  Edgbaston        2   3.2    Australia   
3571   1119542   2018  2018-06-27  Edgbaston        2   3.3    Australia   
3572   1119542   2018  2018-06-27  Edgbaston        2   3.4    Australia   
3573   1119542   2018  2018-06-27  Edgbaston        2   3.5    Australia   
3574   1119542   2018  2018-06-27  Edgbaston        2   3.6    Australia   
3575   1119542   2018  2018-06-27  Edgbaston        2   3.7    Australia   

     bowling_team     striker non_striker     bowler  runs_off_bat  extras  \
3569      England  GJ Maxwell    AJ Finch  CJ Jordan             2       0   
3570      England  GJ Maxwell    AJ Finch  CJ Jordan             2       0   
3571      England  GJ Maxwell    AJ Finch  CJ Jordan             0       1   
3572      England  GJ Maxwell    AJ Finch  CJ Jordan             4       0   
3573      England  GJ Maxwell    AJ Finch  CJ Jordan             0       0   
3574      England     TM Head    AJ Finch  CJ Jordan             5       0   
3575      England    AJ Finch     TM Head  CJ Jordan             1       0   

      wides  noballs  byes  legbyes  penalty wicket_type player_dismissed  \
3569    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
3570    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
3571    NaN      1.0   NaN      NaN      NaN         NaN              NaN   
3572    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
3573    NaN      NaN   NaN      NaN      NaN      bowled       GJ Maxwell   
3574    NaN      NaN   NaN      NaN      NaN         NaN              NaN   
3575    NaN      NaN   NaN      NaN      NaN         NaN              NaN   

      other_wicket_type  other_player_dismissed match_id_innings  time_idx  \
3569                NaN                     NaN        1119542_2        20   
3570                NaN                     NaN        1119542_2        21   
3571                NaN                     NaN        1119542_2        22   
3572                NaN                     NaN        1119542_2        23   
3573                NaN                     NaN        1119542_2        24   
3574                NaN                     NaN        1119542_2        25   
3575                NaN                     NaN        1119542_2        26   

      total_runs_off_ball  cum_runs  is_wicket  cum_wickets  runs_prev_3  \
3569                    2        26          0            1            1   
3570                    2        28          0            1            1   
3571                    1        29          0            1            4   
3572                    4        33          0            1            2   
3573                    0        33          1            2            2   
3574                    5        38          0            2            1   
3575                    1        39          0            2            4   

      over_number  powerplay  death_overs        city toss_winner  \
3569            4          1            0  Birmingham   Australia   
3570            4          1            0  Birmingham   Australia   
3571            4          1            0  Birmingham   Australia   
3572            4          1            0  Birmingham   Australia   
3573            4          1            0  Birmingham   Australia   
3574            4          1            0  Birmingham   Australia   
3575            4          1            0  Birmingham   Australia   

     toss_decision  legal_delivery  legal_delivery_number  balls_remaining  \
3569         field               1                     19              101   
3570         field               1                     20              100   
3571         field               0                     20              100   
3572         field               1                     2

In [39]:
df_all_eng_aus[df_all_eng_aus['other_player_dismissed'].notna()]
# no instances of two wickets on one ball
# looking at the rules it is not possible for this to happen

Empty DataFrame
Columns: [match_id, season, start_date, venue, innings, ball, batting_team, bowling_team, striker, non_striker, bowler, runs_off_bat, extras, wides, noballs, byes, legbyes, penalty, wicket_type, player_dismissed, other_wicket_type, other_player_dismissed, match_id_innings, time_idx, total_runs_off_ball, cum_runs, is_wicket, cum_wickets, runs_prev_3, over_number, powerplay, death_overs, city, toss_winner, toss_decision, legal_delivery, legal_delivery_number, balls_remaining, rob_0, rob_1, rob_2, rob_3, rob_4, rob_6, wicket, extra, other]
Index: []

In [40]:
df_all_eng_aus.shape

(5949, 47)

# **Setting up simple TFT**

I now need to define and split my varibales into 4 groups so that it is suitable for the DARTS documentation
1. Target
2. Past covariates
3. Future Covariates
4. Static covariates

Then we can convert to darts.timeseries objects

Each TimeSeries object is a sequence of data points (balls) within that specific innings

### Imports

In [41]:
!pip install darts


In [42]:
from darts import TimeSeries
from darts.models import TFTModel
from darts.utils.timeseries_generation import datetime_attribute_timeseries
from darts.dataprocessing.transformers import Scaler
from darts.utils.likelihood_models.torch import QuantileRegression
from sklearn.preprocessing import LabelEncoder


/home/svygb4/.pyenv/versions/3.12.2/lib/python3.12/site-packages/fs/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore
/home/svygb4/.pyenv/versions/3.12.2/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [43]:
df_all_eng_aus.head(0)

Empty DataFrame
Columns: [match_id, season, start_date, venue, innings, ball, batting_team, bowling_team, striker, non_striker, bowler, runs_off_bat, extras, wides, noballs, byes, legbyes, penalty, wicket_type, player_dismissed, other_wicket_type, other_player_dismissed, match_id_innings, time_idx, total_runs_off_ball, cum_runs, is_wicket, cum_wickets, runs_prev_3, over_number, powerplay, death_overs, city, toss_winner, toss_decision, legal_delivery, legal_delivery_number, balls_remaining, rob_0, rob_1, rob_2, rob_3, rob_4, rob_6, wicket, extra, other]
Index: []

In [44]:
# specify which columns to extract from the master df
target_cols = ['rob_0', 'rob_1', 'rob_2', 'rob_3', 'rob_4', 'rob_6', 'wicket', 'extra', 'other']
past_cov_cols = ['time_idx', 'over_number', 'cum_runs', 'cum_wickets', 'runs_prev_3', 'legal_delivery', 'balls_remaining']
future_cov_cols = ['powerplay', 'death_overs', 'over_number']
static_cov_cols = ['venue', 'toss_winner', 'toss_decision']

#still need to encode static variables

Label encode statics as Darts expects all covariates to be numeric

In [45]:
# Label encode static covariates, each venue will have a unique number same with toss winner, toss decision
for col in ['venue', 'toss_winner', 'toss_decision']:
    df_all_eng_aus[col] = LabelEncoder().fit_transform(df_all_eng_aus[col].astype(str))



### Convert innings to darts time series

In [46]:

# Convert each innings into TimeSeries format
def create_series_grouped(df):
    target_series = []
    past_cov_series = []
    future_cov_series = []
    static_covs = []

    for _, group in df.groupby("match_id_innings"):
        group = group.sort_values("time_idx")
# group each innings and then ensure order by time_idx

        ts_target = TimeSeries.from_dataframe(group, value_cols=target_cols, time_col="time_idx")
        ts_past = TimeSeries.from_dataframe(group, value_cols=past_cov_cols, time_col="time_idx")
        ts_future = TimeSeries.from_dataframe(group, value_cols=future_cov_cols, time_col="time_idx")
        ts_static = group[static_cov_cols].iloc[0].to_numpy(dtype=np.float32) # convert to float as this is what darts expects
# create Timeseries for each of our targets and covariates

        target_series.append(ts_target)
        past_cov_series.append(ts_past)
        future_cov_series.append(ts_future)
        static_covs.append(ts_static)
# append will add innings by innings

    return target_series, past_cov_series, future_cov_series, static_covs

# Run it
target_series, past_covs, future_covs, static_covs = create_series_grouped(df_all_eng_aus)


In [47]:
print(static_covs)

[array([1., 0., 1.], dtype=float32), array([1., 0., 1.], dtype=float32), array([7., 0., 1.], dtype=float32), array([7., 0., 1.], dtype=float32), array([3., 0., 1.], dtype=float32), array([3., 0., 1.], dtype=float32), array([16.,  0.,  1.], dtype=float32), array([16.,  0.,  1.], dtype=float32), array([16.,  0.,  0.], dtype=float32), array([16.,  0.,  0.], dtype=float32), array([16.,  0.,  1.], dtype=float32), array([16.,  0.,  1.], dtype=float32), array([2., 1., 1.], dtype=float32), array([2., 1., 1.], dtype=float32), array([10.,  0.,  1.], dtype=float32), array([10.,  0.,  1.], dtype=float32), array([6., 0., 1.], dtype=float32), array([6., 0., 1.], dtype=float32), array([6., 0., 1.], dtype=float32), array([6., 0., 1.], dtype=float32), array([17.,  1.,  1.], dtype=float32), array([17.,  1.,  1.], dtype=float32), array([13.,  1.,  1.], dtype=float32), array([13.,  1.,  1.], dtype=float32), array([5., 1., 1.], dtype=float32), array([5., 1., 1.], dtype=float32), array([16.,  1.,  0.], dtyp

In [48]:
df_all_eng_aus['match_id'].nunique()


26

In [49]:
df_all_eng_aus['match_id_innings'].nunique()

52

In [50]:
len(target_series)

52

In [51]:
len(past_covs)

52

In [52]:
# check what the first time series looks like

print("Target Series[0] shape:", target_series[0].values().shape)
print("Target Series[0] sample values:\n", target_series[0].values()[:5])


print("\nPast Covariates[0] shape:", past_covs[0].values().shape)
print("Past Covariates[0] sample values:\n", past_covs[0].values()[:5])


print("\nFuture Covariates[0] shape:", future_covs[0].values().shape)
print("Future Covariates[0] sample values:\n", future_covs[0].values()[:5])


print("\nStatic Covariates[0] shape:", static_covs[0].shape)
print("Static Covariates[0] values:", static_covs[0])

# the shape being 124 is the number of balls

Target Series[0] shape: (124, 9)
Target Series[0] sample values:
 [[0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]]

Past Covariates[0] shape: (124, 7)
Past Covariates[0] sample values:
 [[  1.   1.   2.   0.   0.   1. 119.]
 [  2.   1.   2.   0.   0.   1. 118.]
 [  3.   1.   3.   0.   0.   0. 118.]
 [  4.   1.   7.   0.   2.   1. 117.]
 [  5.   1.   9.   0.   0.   1. 116.]]

Future Covariates[0] shape: (124, 3)
Future Covariates[0] sample values:
 [[1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]

Static Covariates[0] shape: (3,)
Static Covariates[0] values: [1. 0. 1.]


### Train Val Test split

In [53]:
from sklearn.model_selection import train_test_split

train_targets, test_targets, train_past, test_past, train_future, test_future, train_static, test_static = train_test_split(
    target_series, past_covs, future_covs, static_covs, test_size=0.15, random_state=42
)
# getting the test set

train_targets, val_targets, train_past, val_past, train_future, val_future, train_static, val_static = train_test_split(
    train_targets, train_past, train_future, train_static, test_size=0.18, random_state=42
)
# split remaining samples into train and val sets

# check how many samples in each set
print(f"Train samples: {len(train_targets)}")
print(f"Validation samples: {len(val_targets)}")
print(f"Test samples: {len(test_targets)}")


Train samples: 36
Validation samples: 8
Test samples: 8


Here I have split my samples into a 15% test set and 85% train set 

each set contains target/past/future/static splits whihc must be aligned 

Train set is then aplit agian into train and val (o.18 ¬ 15% of original data) set 

Have had to add this filter because some innings where to short

**Need to deal with this - not to self**

In [54]:
# Get the TimeSeries at index 18
ts_example = train_targets[18]

# index 18 was to short
print(f"Length of innings at index 18: {len(ts_example)}")
print("Time index:", ts_example.time_index)
print("Values:")
print(ts_example.values())


Length of innings at index 18: 10
Time index: RangeIndex(start=1, stop=11, step=1, name='time_idx')
Values:
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [55]:
def filter_short_series(targets, past, future, static, min_len=31):
    filtered = [
        (t, p, f, s)
        for t, p, f, s in zip(targets, past, future, static)
        if len(t) >= min_len
    ]
    return zip(*filtered) if filtered else ([], [], [], [])

# Apply to each dataset
train_targets, train_past, train_future, train_static = filter_short_series(
    train_targets, train_past, train_future, train_static
)
val_targets, val_past, val_future, val_static = filter_short_series(
    val_targets, val_past, val_future, val_static
)
test_targets, test_past, test_future, test_static = filter_short_series(
    test_targets, test_past, test_future, test_static
)


Goes through each innings in each df (T/S/P/F) and only keeps innings which are at least 31 balls long 
Applies it seperatley to train/val/test sets 

### Scale
Only need to scale past and future covariates

In [56]:
# scale past covariates
scaler_past = Scaler()
train_past_scaled = scaler_past.fit_transform(train_past)
# fit and scale train set
val_past_scaled = scaler_past.transform(val_past)
test_past_scaled = scaler_past.transform(test_past)
# dont fit scaler just apply

# Scale future covariates
scaler_future = Scaler()
# new scaler
train_future_scaled = scaler_future.fit_transform(train_future)
# fit and scale on train set
val_future_scaled = scaler_future.transform(val_future)
test_future_scaled = scaler_future.transform(test_future)
# just scale train and val set


train_targets = [ts.with_static_covariates(pd.Series(sc, index=static_cov_cols)) for ts, sc in zip(train_targets, train_static)]
val_targets = [ts.with_static_covariates(pd.Series(sc, index=static_cov_cols)) for ts, sc in zip(val_targets, val_static)]
test_targets = [ts.with_static_covariates(pd.Series(sc, index=static_cov_cols)) for ts, sc in zip(test_targets, test_static)]

#insert the static covariates back in. When using .with_static_covariates needs to be a pd series or pd df
#loops once per innings and inserts my static covariates

Only 8 TimeSeries (lists) were provided which is lower than the number of series (n=35) used to fit Scaler. This can result in a mismatch between the series and the underlying transformers.
Only 7 TimeSeries (lists) were provided which is lower than the number of series (n=35) used to fit Scaler. This can result in a mismatch between the series and the underlying transformers.
Only 8 TimeSeries (lists) were provided which is lower than the number of series (n=35) used to fit Scaler. This can result in a mismatch between the series and the underlying transformers.
Only 7 TimeSeries (lists) were provided which is lower than the number of series (n=35) used to fit Scaler. This can result in a mismatch between the series and the underlying transformers.


Fit scaler on only training sets 
Then scale train/test/val 

only done to past and futurue covariates 
add back in static covariates after filter (above) removed them 
statics only need to be added to targets 

Sanity checks 

In [57]:
# Are statics attached?
train_targets[3].static_covariates  # should show a Series/DataFrame with venue, toss_winner, toss_decision

static_covariates  venue  toss_winner  toss_decision
global_components    1.0          0.0            1.0

In [58]:
print(len(train_past))
print(len(val_past))
print(len(test_past))

35
8
7


### Model Setup

In [59]:
quantiles = [0.1, 0.5, 0.9]  # Adjust later if needed

model = TFTModel(
    input_chunk_length=30,       # look sback 30 balls, can chnage this
    output_chunk_length=1,       # predict 1 ball
    hidden_size=32,              # lightweight start, can increase
    lstm_layers=1,               # single layer to start as not much data
    num_attention_heads=4,       # darts reccomended default
    dropout=0.1,                 # prevent overfitting
    batch_size=32,               # efficeint to start, could increase if switch compute
    n_epochs=50,                 # default is 100, short to start then increase
    add_relative_index=True,     # adds positional value to future covariates
    likelihood=QuantileRegression(quantiles=quantiles),   #default
    random_state=42,
    force_reset=True,            #training resets each time
)


### Try without future covariates

#### .fit

In [60]:
model.fit(
    series=train_targets,
    past_covariates=train_past_scaled,
    verbose=True,
)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs



   | Name                              | Type                             | Params | Mode 
------------------------------------------------------------------------------------------------
0  | train_metrics                     | MetricCollection                 | 0      | train
1  | val_metrics                       | MetricCollection                 | 0      | train
2  | input_embeddings                  | _MultiEmbedding                  | 0      | train
3  | static_covariates_vsn             | _VariableSelectionNetwork        | 2.8 K  | train
4  | encoder_vsn                       | _VariableSelectionNetwork        | 19.1 K | train
5  | decoder_vsn                       | _VariableSelectionNetwork        | 896    | train
6  | static_context_grn                | _GatedResidualNetwork            | 4.3 K  | train
7  | static_context_hidden_encoder_grn | _GatedResidualNetwork            | 4.3 K  | train
8  | static_context_cell_encoder_grn   | _GatedResidualNetwork            | 4.3 K  

Epoch 13:  11%|█         | 12/110 [00:00<00:07, 12.82it/s, train_loss=0.120] 

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x7f91c52858e0>>
Traceback (most recent call last):
  File "/home/svygb4/.pyenv/versions/3.12.2/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 781, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(

KeyboardInterrupt: 


Epoch 49: 100%|██████████| 110/110 [00:09<00:00, 11.94it/s, train_loss=0.142] 

`Trainer.fit` stopped: `max_epochs=50` reached.


Epoch 49: 100%|██████████| 110/110 [00:09<00:00, 11.94it/s, train_loss=0.142]


TFTModel(output_chunk_shift=0, hidden_size=32, lstm_layers=1, num_attention_heads=4, full_attention=False, feed_forward=GatedResidualNetwork, dropout=0.1, hidden_continuous_size=8, categorical_embedding_sizes=None, add_relative_index=True, loss_fn=None, likelihood=QuantileRegression(quantiles=[0.1, 0.5, 0.9], prior_strength=1.0), norm_type=LayerNorm, use_static_covariates=True, input_chunk_length=30, output_chunk_length=1, batch_size=32, n_epochs=50, random_state=42, force_reset=True)

In [62]:
# Do lengths line up with input_chunk_length?
len(train_targets[0]) >= model.input_chunk_length + model.output_chunk_length  

True

In [63]:
# Do covariate indexes align?
train_past_scaled[0].time_index.equals(train_targets[0].time_index)  


True

In [64]:
train_future_scaled[0].time_index.equals(train_targets[0].time_index)      

True

#### .predict

In [65]:
val_preds = model.predict(
    n=1, 
    series=val_targets,
    past_covariates=val_past_scaled,
)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 53.36it/s]


This .predict makes a prediction at the end of each time series, so hypothetically predicts the ball after the end of each innings 
We want to have a rolling prediction, that makes a prediction at each ball 
This will allow the model to recognise patterns as the game develops and will allow us to compare our predictions to the actual outcome 

In [66]:
assert len(val_preds) == len(val_targets)
assert all(len(ts) == 1 for ts in val_preds)  # each forecast is 1 step
print("Example first vector:", val_preds[0].all_values()[-1])


Example first vector: [[ 1.00281461e+00]
 [ 7.52714565e-01]
 [-1.52458675e-02]
 [-3.40274390e-03]
 [-1.43287662e-03]
 [ 7.33531214e-03]
 [-8.01463752e-04]
 [ 1.35833578e-03]
 [-4.80498594e-03]]


So without future covariates .predict works 

Now lets check we can get probabilities for each output variable 

#### probabilities

In [67]:
# extract raw output for next ball 
arr = val_preds[0].all_values(copy=False)
arr = np.asarray(arr, dtype=float)
arr = np.squeeze(arr)          # drop size-1 dims -> e.g. (time, comps) or (comps,)
if arr.ndim == 2:
    raw_vec = arr[-1]          # take last time step -> shape (comps,)
elif arr.ndim == 1:
    raw_vec = arr
else:
    # squeeze to get 2d output
    raw_vec = np.squeeze(arr)[-1]

print("raw_vec shape:", raw_vec.shape)  


# this gives us the raw output vector for the next ball, which is a 1D array of probabilities for each target variable

raw_vec shape: (9,)


In [68]:
# Softmax to convert to probabilities
def softmax1d(x):
    x = x - np.max(x)          # numerical stability
    ex = np.exp(x)
    return ex / ex.sum()

probs = softmax1d(raw_vec)      # shape (9,)

# print probabilities of each target variable
for name, p in zip(val_preds[0].components, probs.tolist()):
    print(f"{name:>7}: {p:.4f}")
print("Sum:", float(probs.sum()))

  rob_0: 0.2304
  rob_1: 0.1794
  rob_2: 0.0832
  rob_3: 0.0842
  rob_4: 0.0844
  rob_6: 0.0851
 wicket: 0.0844
  extra: 0.0846
  other: 0.0841
Sum: 1.0000000000000002


In [69]:
print("Probabilities sum to 1:", np.isclose(probs.sum(), 1.0))

Probabilities sum to 1: True


### Future covariates added 
Doesnt work at th momemnt 

Fit model

series = what we are trying to predict, aka our targets 
past_covariates = time varying features know up to prediction 
future_covariartes = stuff we know in the future 

In [124]:
model.fit(
    series=train_targets,
    past_covariates=train_past_scaled,
    future_covariates=train_future_scaled,
    verbose=True
)

# not how long this model takes to fit even with the current set up
# it took 9 mins (8 mins faster than colab) to fit on 50 epochs with 32 batch size and 1 layer

ValueError: The dimensionality of the series in the training set do not match the dimensionality of the series the model has previously been trained on. Model input/output dimensions = [9, 7, None, None, 3, 9], provided input/output dimensions = [9, 7, 3, 3, 3, 9]


ValueError: The dimensionality of the series in the training set do not match the dimensionality of the series the model has previously been trained on. Model input/output dimensions = [9, 7, None, None, 3, 9], provided input/output dimensions = [9, 7, 3, 3, 3, 9]

Make predictions on val

In [ ]:
# Trim only target and past covariates
val_targets_trimmed = [ts[:-1] for ts in val_targets]
val_past_trimmed = [ts[:-1] for ts in val_past_scaled]
# DO NOT TRIM future covariates
val_future_trimmed = val_future_scaled

# Predict 1 step ahead
val_predictions = model.predict(
    n=1,
    series=val_targets_trimmed,
    past_covariates=val_past_trimmed,
    future_covariates=val_future_trimmed,
    num_samples=100
)


GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs


Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00,  1.49it/s]


In [ ]:
val_predictions = model.predict(
    n=1,  # predict one step ahead (since your output_chunk_length=1)
    series=val_targets,
    past_covariates=val_past_scaled,
    future_covariates=val_future_scaled,
    num_samples=100
)


ValueError: For the given forecasting horizon `n=1`, the provided `future_covariates` at series sequence index `0` do not extend far enough into the future. As `n <= output_chunk_length` the `future_covariates` must end at or after time step `122`, whereas now the end is at time step `121`.


ValueError: For the given forecasting horizon `n=1`, the provided `future_covariates` at series sequence index `0` do not extend far enough into the future. As `n <= output_chunk_length` the `future_covariates` must end at or after time step `122`, whereas now the end is at time step `121`.

In [ ]:
val_predictions[0].plot(label="Predicted")
val_targets[0].plot(label="Actual")


Ananlysis

In [ ]:
# Actual class probability
# Combine all actual target series from the validation set
actual_vals = pd.concat([ts.pd_dataframe() for ts in val_targets])

# Compute mean for each class
actual_class_probs = actual_vals.mean()
print("Actual Class Probabilities:")
print(actual_class_probs)


In [ ]:
#Predicted class probability
# Convert all probabilistic predictions to means
predicted_vals = pd.concat([ts.mean(axis=0).pd_dataframe() for ts in val_predictions])

# Compute mean predicted probability for each class
predicted_class_probs = predicted_vals.mean()
print("Predicted Class Probabilities:")
print(predicted_class_probs)


In [ ]:
#Compare
comparison_df = pd.DataFrame({
    "Actual": actual_class_probs,
    "Predicted": predicted_class_probs
})

print(comparison_df)


In [ ]:
import matplotlib.pyplot as plt

# Combine into a single df
comparison_df = pd.DataFrame({
    "Actual": actual_class_probs,
    "Predicted": predicted_class_probs
})

# Plot
comparison_df.plot(kind='bar', figsize=(10, 6))
plt.title("Predicted vs Actual Class Probabilities (Validation Set)")
plt.ylabel("Probability")
plt.xlabel("Outcome Class")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()
